menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  标签: { id: tags, url: /tags }
  分类: { id: categories, url: /categories }
  关于: { id: curriculumvitae, url: /curriculumvitae }
  链接: { id: links, url: /links }

github: YOUR_GITHUB_NAME

background-root: /images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]

avatar: /images/avatar.gif

#### Comment
duoshuo: 
  short_name: YOUR_DUOSHUO_SHORT_NAME    ## duoshuo short name.
                                         ## refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d

rss: YOUR_RSS_ADDRESS                    ## if any...
